name: OnlineModeFix
version: 1.1.4
description: Fixes online-mode authentication.
author: craftycodie
authors: [Codie]
website: https://linktr.ee/craftycodie

main: gg.codie.mineonline.plugin.bukkit.OnlineModeFixPlugin
database: false
depend: []